### ISSUE TITLE
Type != Implementation

### ISSUE THREAD

**Issue by furey** [tsmx/human-readable#2]
Hi,

Thanks for creating this library!

Just noticed the following type name…

https://github.com/tsmx/human-readable/blob/master/human-readable.js#L133

…does not match its implementation name:

https://github.com/tsmx/human-readable/blob/master/human-readable.d.ts#L14

**TL;DR:** `calcFromTo` != `fromTo`

Cheers.

**Comment by tsmx** [comment]
Hi,

You're welcome and thank you very much for finding out this issue. I think changing the name in the `.d.ts` file to `fromTo` would be the best way to solve it.

Please correct me if I'm wrong but this would incorporate a breaking change at least for TS users. Major version number increase needed? Appreciate your view on this.

Kind regards,
Sebastian

**Comment by furey** [comment]
Hi Sebastian,

Just submitted a PR with the fix (https://github.com/tsmx/human-readable/pull/3).

While the PR is technically a patch bump (`1.0.9` → `1.0.10`), I'd use a major bump just to be safe (`1.0.9` → `2.0.0`).

Cheers.

**Comment by tsmx** [comment]
Hi,

PR is merged and v2.0.0 released. Thank you very much for your contribution - appreciate it! 

:+1: 

Closing this issue.

**Comment by furey** [comment]
@tsmx No worries—have a good one! 😎
